export const Text = {
    Title: {'en':'About Harck-CMS', 'pt':'Sobre Harck-CMS', 'ru':'О Harck-CMS'},
    TitleDescription: {'en':'An open-source Content Management System. Provided by Harckade under the MIT license', 'pt':'Um sistema de gestão de conteúdo de código aberto. Disponibilizado por Harckade sob a licença MIT', 'ru':'Система управления контентом с открытым исходным кодом. Предоставлена Harckade под лицензией MIT'},
    License: {'en':'MIT License', 'pt':'Licença MIT', 'ru':'Лицензия MIT'},
    Copyright:{'en':'Copyright (c) 2023 Harckade','pt':'Copyright (c) 2023 Harckade', 'ru':'Copyright (c) 2023 Harckade'},
    Par1:{'en':'Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:',
          'pt':'A permissão é concedida através do presente, sem custos, a qualquer pessoa que esteja a obter uma cópia deste software e ficheiros de documentação associada (o “Software”), para processar o Software sem restrição, incluindo sem limitação os direitos de utilizar, copiar, modificar, fundir, publicar, distribuir, sublicenciar e/ou vender cópias do Software, e para permitir que as pessoas a quem este Software foi fornecido o façam, estando sujeitas às seguintes condições:', 
          'ru':'Данная лицензия разрешает, безвозмездно, лицам, получившим копию данного программного обеспечения и сопутствующей документации (в дальнейшем именуемыми "Программное Обеспечение"), использовать Программное Обеспечение без ограничений, включая неограниченное право на использование, копирование, изменение, объединение, публикацию, распространение, сублицензирование и/или продажу копий Программного Обеспечения, также как и лицам, которым предоставляется данное Программное Обеспечение, при соблюдении следующих условий:'},
    Par2:{'en':'The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.',
          'pt':'A notificação relativa a direitos de autor supramencionada e esta notificação de permissão deverão ser incluídas em todas as cópias ou partes substanciais do Software.', 
          'ru':'Вышеупомянутый копирайт и данные условия должны быть включены во все копии или значимые части данного Программного Обеспечения.'},
    Par3:{'en':'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.',
          'pt':'O SOFTWARE É FORNECIDO “TAL COMO ESTÁ”, SEM NENHUM TIPO DE GARANTIA, EXPRESSA OU IMPLÍCITA, INCLUINDO, MAS SEM LIMITAÇÃO, AS GARANTIAS DE COMERCIALIZAÇÃO, ADEQUAÇÃO A UM FIM ESPECÍFICO E NÃO VIOLAÇÃO DE DIREITOS DE PROPRIEDADE INTELECTUAL. EM CASO ALGUM SERÃO OS AUTORES OU DETENTORES DE DIREITOS DE AUTOR RESPONSÁVEIS POR QUAISQUER AÇÕES JUDICIAIS, DANOS OU QUAISQUER OUTRAS RESPONSABILIDADES, QUER NUMA AÇÃO DE CONTRATO, ATO ILÍCITO OU NOUTRA AÇÃO, RESULTANTE DE, DECORRENTE DE OU RELACIONADA COM O SOFTWARE OU A UTILIZAÇÃO OU OUTRAS TRANSAÇÕES NO SOFTWARE.',
          'ru':'ДАННОЕ ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЯЕТСЯ «КАК ЕСТЬ», БЕЗ ЛЮБОГО ВИДА ГАРАНТИЙ, ЯВНО ВЫРАЖЕННЫХ ИЛИ ПОДРАЗУМЕВАЕМЫХ, ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ ГАРАНТИЯМИ ТОВАРНОЙ ПРИГОДНОСТИ, СООТВЕТСТВИЯ ПО ЕГО КОНКРЕТНОМУ НАЗНАЧЕНИЮ И НЕНАРУШЕНИЯ ПРАВ. НИ В КАКОМ СЛУЧАЕ АВТОРЫ ИЛИ ПРАВООБЛАДАТЕЛИ НЕ НЕСУТ ОТВЕТСТВЕННОСТИ ПО ИСКАМ О ВОЗМЕЩЕНИИ УЩЕРБА, УБЫТКОВ ИЛИ ДРУГИХ ТРЕБОВАНИЙ ПО ДЕЙСТВУЮЩИМ КОНТРАКТАМ, ДЕЛИКТАМ ИЛИ ИНОМУ, ВОЗНИКШИМ ИЗ, ИМЕЮЩИМ ПРИЧИНОЙ ИЛИ СВЯЗАННЫМ С ПРОГРАММНЫМ ОБЕСПЕЧЕНИЕМ ИЛИ ИСПОЛЬЗОВАНИЕМ ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ ИЛИ ИНЫМИ ДЕЙСТВИЯМИ С ПРОГРАММНЫМ ОБЕСПЕЧЕНИЕМ.'}
}