name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  repository_dispatch:
    types: [backend_automation]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Setup publish-profile and app-name env variables
        run: |
          echo "SERVER_ADDRESS=${{secrets.SERVER_ADDRESS}}" >> $GITHUB_ENV
          echo "YOUR_WEBSITE_URL=${{secrets.YOUR_WEBSITE_URL}}" >> $GITHUB_ENV
          echo "GA_TRACKING_ID=${{secrets.GA_TRACKING_ID}}" >> $GITHUB_ENV
          echo "AZURE_STATIC_WEB_APPS_API_TOKEN=${{secrets.AZURE_STATIC_WEB_APPS_API_TOKEN}}" >> $GITHUB_ENV
          echo "YOUR_PRIVACY_EMAIL=${{secrets.YOUR_PRIVACY_EMAIL}}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "/" # App source code path relative to repository root
          output_location: "public" # Built app content directory, relative to app_location - optional
          app_build_command: 'npm run-script build'
          api_build_command: 'rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache'
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
